artifacts:
  - name: "@daiyam/artifact-base"
    version: 0.4.0
  - name: "@daiyam/artifact-lang-ts"
    version: 0.3.2
  - name: "@daiyam/artifact-npm-ts"
    version: 0.1.2
  - name: "@daiyam/artifact-npm-daiyam"
    version: 0.1.0
  - name: "@daiyam/artifact-test-mocha-ts"
    version: 0.3.0
